[package]
name = "datamodel-derive"
version = "0.2.0"
edition = "2024"
authors = ["NameIsJakob"]
description = "Derive macro to implement ElementClass for datamodel-rs"
repository = "https://github.com/NameIsJakob/datamodel-rs/"
license = "MIT"
keywords = ["derive"]
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
syn = "3.0.6"
quote = "1.0.47"
proc-macro-crate = "3.5.0"
proc-macro2 = "1.0.107"
